"""fix ingredients and some other tables

Revision ID: de808794b7ba
Revises: dfa04fd9cc06
Create Date: 2024-11-14 21:07:45.858454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de808794b7ba'
down_revision: Union[str, None] = 'dfa04fd9cc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('organization_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'organizations', ['organization_id'], ['id'])
    op.alter_column('tasks', 'food_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'food_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'organization_id')
    # ### end Alembic commands ###
