"""add name and username in workers

Revision ID: 0745adc8e1fb
Revises: 082d2ac90abc
Create Date: 2024-10-30 08:44:14.607390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0745adc8e1fb'
down_revision: Union[str, None] = '082d2ac90abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('name', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'username')
    op.drop_column('workers', 'name')
    # ### end Alembic commands ###
