"""add possible_ingredients table

Revision ID: 1a847689caa1
Revises: de808794b7ba
Create Date: 2024-11-15 19:28:54.462638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a847689caa1'
down_revision: Union[str, None] = 'de808794b7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possible_ingredients',
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('food_id', 'ingredient_id')
    )
    op.drop_constraint('ingredients_food_id_fkey', 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'food_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('food_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('ingredients_food_id_fkey', 'ingredients', 'foods', ['food_id'], ['id'])
    op.drop_table('possible_ingredients')
    # ### end Alembic commands ###
