"""review some tables

Revision ID: dfa04fd9cc06
Revises: 0745adc8e1fb
Create Date: 2024-11-13 21:40:10.792478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa04fd9cc06'
down_revision: Union[str, None] = '0745adc8e1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_ingredients',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'ingredient_id')
    )

    op.drop_constraint('food_orders_description_food_id_fkey', 'food_orders_description', type_='foreignkey')

    op.drop_table('food')
    op.drop_table('food_groups')
    op.drop_table('food_orders_description')
    op.add_column('tasks', sa.Column('food_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'foods', ['food_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'food_id')
    op.create_table('food_orders_description',
    sa.Column('task_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='food_orders_description_food_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='food_orders_description_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'food_id', name='food_orders_description_pkey')
    )
    op.create_table('food_groups',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('food_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='food_groups_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='food_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('food',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('food_group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_group_id'], ['food_groups.id'], name='food_food_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='food_pkey')
    )
    op.drop_table('task_ingredients')
    op.drop_table('ingredients')
    op.drop_table('foods')
    # ### end Alembic commands ###
